=begin
#Public Api v3

#Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.

The version of the OpenAPI document: 3.0
Contact: contact@yousign.com
Generated by: https://openapi-generator.tech
Generator version: 7.11.0

=end

require 'date'
require 'time'

module YousignClientV3
  class ConsumptionApi
    attr_accessor :electronic_signature

    attr_accessor :advanced_electronic_signature

    attr_accessor :advanced_electronic_signature_with_qualified_certificate

    attr_accessor :electronic_seal

    attr_accessor :advanced_electronic_seal

    attr_accessor :qualified_electronic_signature_identification_mode

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'electronic_signature' => :'electronic_signature',
        :'advanced_electronic_signature' => :'advanced_electronic_signature',
        :'advanced_electronic_signature_with_qualified_certificate' => :'advanced_electronic_signature_with_qualified_certificate',
        :'electronic_seal' => :'electronic_seal',
        :'advanced_electronic_seal' => :'advanced_electronic_seal',
        :'qualified_electronic_signature_identification_mode' => :'qualified_electronic_signature_identification_mode'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'electronic_signature' => :'Integer',
        :'advanced_electronic_signature' => :'Integer',
        :'advanced_electronic_signature_with_qualified_certificate' => :'Integer',
        :'electronic_seal' => :'Integer',
        :'advanced_electronic_seal' => :'Integer',
        :'qualified_electronic_signature_identification_mode' => :'ConsumptionAppQualifiedElectronicSignatureIdentificationMode'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `YousignClientV3::ConsumptionApi` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `YousignClientV3::ConsumptionApi`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'electronic_signature')
        self.electronic_signature = attributes[:'electronic_signature']
      else
        self.electronic_signature = nil
      end

      if attributes.key?(:'advanced_electronic_signature')
        self.advanced_electronic_signature = attributes[:'advanced_electronic_signature']
      else
        self.advanced_electronic_signature = nil
      end

      if attributes.key?(:'advanced_electronic_signature_with_qualified_certificate')
        self.advanced_electronic_signature_with_qualified_certificate = attributes[:'advanced_electronic_signature_with_qualified_certificate']
      else
        self.advanced_electronic_signature_with_qualified_certificate = nil
      end

      if attributes.key?(:'electronic_seal')
        self.electronic_seal = attributes[:'electronic_seal']
      end

      if attributes.key?(:'advanced_electronic_seal')
        self.advanced_electronic_seal = attributes[:'advanced_electronic_seal']
      end

      if attributes.key?(:'qualified_electronic_signature_identification_mode')
        self.qualified_electronic_signature_identification_mode = attributes[:'qualified_electronic_signature_identification_mode']
      else
        self.qualified_electronic_signature_identification_mode = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @electronic_signature.nil?
        invalid_properties.push('invalid value for "electronic_signature", electronic_signature cannot be nil.')
      end

      if @electronic_signature < 0
        invalid_properties.push('invalid value for "electronic_signature", must be greater than or equal to 0.')
      end

      if @advanced_electronic_signature.nil?
        invalid_properties.push('invalid value for "advanced_electronic_signature", advanced_electronic_signature cannot be nil.')
      end

      if @advanced_electronic_signature < 0
        invalid_properties.push('invalid value for "advanced_electronic_signature", must be greater than or equal to 0.')
      end

      if @advanced_electronic_signature_with_qualified_certificate.nil?
        invalid_properties.push('invalid value for "advanced_electronic_signature_with_qualified_certificate", advanced_electronic_signature_with_qualified_certificate cannot be nil.')
      end

      if @advanced_electronic_signature_with_qualified_certificate < 0
        invalid_properties.push('invalid value for "advanced_electronic_signature_with_qualified_certificate", must be greater than or equal to 0.')
      end

      if !@electronic_seal.nil? && @electronic_seal < 0
        invalid_properties.push('invalid value for "electronic_seal", must be greater than or equal to 0.')
      end

      if !@advanced_electronic_seal.nil? && @advanced_electronic_seal < 0
        invalid_properties.push('invalid value for "advanced_electronic_seal", must be greater than or equal to 0.')
      end

      if @qualified_electronic_signature_identification_mode.nil?
        invalid_properties.push('invalid value for "qualified_electronic_signature_identification_mode", qualified_electronic_signature_identification_mode cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @electronic_signature.nil?
      return false if @electronic_signature < 0
      return false if @advanced_electronic_signature.nil?
      return false if @advanced_electronic_signature < 0
      return false if @advanced_electronic_signature_with_qualified_certificate.nil?
      return false if @advanced_electronic_signature_with_qualified_certificate < 0
      return false if !@electronic_seal.nil? && @electronic_seal < 0
      return false if !@advanced_electronic_seal.nil? && @advanced_electronic_seal < 0
      return false if @qualified_electronic_signature_identification_mode.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] electronic_signature Value to be assigned
    def electronic_signature=(electronic_signature)
      if electronic_signature.nil?
        fail ArgumentError, 'electronic_signature cannot be nil'
      end

      if electronic_signature < 0
        fail ArgumentError, 'invalid value for "electronic_signature", must be greater than or equal to 0.'
      end

      @electronic_signature = electronic_signature
    end

    # Custom attribute writer method with validation
    # @param [Object] advanced_electronic_signature Value to be assigned
    def advanced_electronic_signature=(advanced_electronic_signature)
      if advanced_electronic_signature.nil?
        fail ArgumentError, 'advanced_electronic_signature cannot be nil'
      end

      if advanced_electronic_signature < 0
        fail ArgumentError, 'invalid value for "advanced_electronic_signature", must be greater than or equal to 0.'
      end

      @advanced_electronic_signature = advanced_electronic_signature
    end

    # Custom attribute writer method with validation
    # @param [Object] advanced_electronic_signature_with_qualified_certificate Value to be assigned
    def advanced_electronic_signature_with_qualified_certificate=(advanced_electronic_signature_with_qualified_certificate)
      if advanced_electronic_signature_with_qualified_certificate.nil?
        fail ArgumentError, 'advanced_electronic_signature_with_qualified_certificate cannot be nil'
      end

      if advanced_electronic_signature_with_qualified_certificate < 0
        fail ArgumentError, 'invalid value for "advanced_electronic_signature_with_qualified_certificate", must be greater than or equal to 0.'
      end

      @advanced_electronic_signature_with_qualified_certificate = advanced_electronic_signature_with_qualified_certificate
    end

    # Custom attribute writer method with validation
    # @param [Object] electronic_seal Value to be assigned
    def electronic_seal=(electronic_seal)
      if electronic_seal.nil?
        fail ArgumentError, 'electronic_seal cannot be nil'
      end

      if electronic_seal < 0
        fail ArgumentError, 'invalid value for "electronic_seal", must be greater than or equal to 0.'
      end

      @electronic_seal = electronic_seal
    end

    # Custom attribute writer method with validation
    # @param [Object] advanced_electronic_seal Value to be assigned
    def advanced_electronic_seal=(advanced_electronic_seal)
      if advanced_electronic_seal.nil?
        fail ArgumentError, 'advanced_electronic_seal cannot be nil'
      end

      if advanced_electronic_seal < 0
        fail ArgumentError, 'invalid value for "advanced_electronic_seal", must be greater than or equal to 0.'
      end

      @advanced_electronic_seal = advanced_electronic_seal
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          electronic_signature == o.electronic_signature &&
          advanced_electronic_signature == o.advanced_electronic_signature &&
          advanced_electronic_signature_with_qualified_certificate == o.advanced_electronic_signature_with_qualified_certificate &&
          electronic_seal == o.electronic_seal &&
          advanced_electronic_seal == o.advanced_electronic_seal &&
          qualified_electronic_signature_identification_mode == o.qualified_electronic_signature_identification_mode
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [electronic_signature, advanced_electronic_signature, advanced_electronic_signature_with_qualified_certificate, electronic_seal, advanced_electronic_seal, qualified_electronic_signature_identification_mode].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = YousignClientV3.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
