=begin
#Public Api v3

#Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.

The version of the OpenAPI document: 3.0
Contact: contact@yousign.com
Generated by: https://openapi-generator.tech
Generator version: 7.11.0

=end

require 'date'
require 'time'

module YousignClientV3
  class CreateSignatureRequest
    # Name of the signature request
    attr_accessor :name

    # Delivery mode to notify signers.
    attr_accessor :delivery_mode

    # Enable an ordered workflow, each signer will be requested to sign in a sequential order
    attr_accessor :ordered_signers

    attr_accessor :reminder_settings

    # Time zone of the dates and times displayed in emails, the Signature Request expiration date, and the PDF Audit Trail. Format: tz database. Default is set to Europe/Paris.
    attr_accessor :timezone

    # A custom note added to emails sent to signers.
    attr_accessor :email_custom_note

    # Due date of the signature request (yyyy-mm-dd). Default to 6 month after the activation.
    attr_accessor :expiration_date

    # Create a signature request from an existing template.
    attr_accessor :template_id

    # Store a custom id that will be added to webhooks & appended to redirect urls.
    attr_accessor :external_id

    # Use a specific branding to customize the signature experience.
    attr_accessor :branding_id

    # Use a specific Custom Experience to customize the signature experience.
    attr_accessor :custom_experience_id

    # You can directly attach orphan documents to the signature request.
    attr_accessor :documents

    # Can only be used if you add documents at the same time.
    attr_accessor :signers

    # Scope the signature request to a specific workspace. If template_id is filled and Template is already linked to a Workspace, keep this field to null ; the created Signature Request will be scoped to Template's Workspace.
    attr_accessor :workspace_id

    # Define the locale for the generated audit trail.
    attr_accessor :audit_trail_locale

    # Allowing signers to decline to sign.
    attr_accessor :signers_allowed_to_decline

    attr_accessor :email_notification

    attr_accessor :template_placeholders

    attr_accessor :archiving

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'name' => :'name',
        :'delivery_mode' => :'delivery_mode',
        :'ordered_signers' => :'ordered_signers',
        :'reminder_settings' => :'reminder_settings',
        :'timezone' => :'timezone',
        :'email_custom_note' => :'email_custom_note',
        :'expiration_date' => :'expiration_date',
        :'template_id' => :'template_id',
        :'external_id' => :'external_id',
        :'branding_id' => :'branding_id',
        :'custom_experience_id' => :'custom_experience_id',
        :'documents' => :'documents',
        :'signers' => :'signers',
        :'workspace_id' => :'workspace_id',
        :'audit_trail_locale' => :'audit_trail_locale',
        :'signers_allowed_to_decline' => :'signers_allowed_to_decline',
        :'email_notification' => :'email_notification',
        :'template_placeholders' => :'template_placeholders',
        :'archiving' => :'archiving'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'name' => :'String',
        :'delivery_mode' => :'String',
        :'ordered_signers' => :'Boolean',
        :'reminder_settings' => :'CreateSignatureRequestReminderSettings',
        :'timezone' => :'String',
        :'email_custom_note' => :'String',
        :'expiration_date' => :'Date',
        :'template_id' => :'String',
        :'external_id' => :'String',
        :'branding_id' => :'String',
        :'custom_experience_id' => :'String',
        :'documents' => :'Array<String>',
        :'signers' => :'Array<CreateSignatureRequestSignersInner>',
        :'workspace_id' => :'String',
        :'audit_trail_locale' => :'AuditTrailLocale',
        :'signers_allowed_to_decline' => :'Boolean',
        :'email_notification' => :'SignatureRequestEmailNotification',
        :'template_placeholders' => :'CreateSignatureRequestTemplatePlaceholders',
        :'archiving' => :'Archiving'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'reminder_settings',
        :'email_custom_note',
        :'external_id',
        :'branding_id',
        :'custom_experience_id',
        :'workspace_id',
        :'audit_trail_locale',
        :'email_notification',
        :'template_placeholders',
        :'archiving'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `YousignClientV3::CreateSignatureRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `YousignClientV3::CreateSignatureRequest`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'delivery_mode')
        self.delivery_mode = attributes[:'delivery_mode']
      else
        self.delivery_mode = nil
      end

      if attributes.key?(:'ordered_signers')
        self.ordered_signers = attributes[:'ordered_signers']
      end

      if attributes.key?(:'reminder_settings')
        self.reminder_settings = attributes[:'reminder_settings']
      end

      if attributes.key?(:'timezone')
        self.timezone = attributes[:'timezone']
      else
        self.timezone = 'Europe/Paris'
      end

      if attributes.key?(:'email_custom_note')
        self.email_custom_note = attributes[:'email_custom_note']
      end

      if attributes.key?(:'expiration_date')
        self.expiration_date = attributes[:'expiration_date']
      end

      if attributes.key?(:'template_id')
        self.template_id = attributes[:'template_id']
      end

      if attributes.key?(:'external_id')
        self.external_id = attributes[:'external_id']
      end

      if attributes.key?(:'branding_id')
        self.branding_id = attributes[:'branding_id']
      end

      if attributes.key?(:'custom_experience_id')
        self.custom_experience_id = attributes[:'custom_experience_id']
      end

      if attributes.key?(:'documents')
        if (value = attributes[:'documents']).is_a?(Array)
          self.documents = value
        end
      end

      if attributes.key?(:'signers')
        if (value = attributes[:'signers']).is_a?(Array)
          self.signers = value
        end
      end

      if attributes.key?(:'workspace_id')
        self.workspace_id = attributes[:'workspace_id']
      end

      if attributes.key?(:'audit_trail_locale')
        self.audit_trail_locale = attributes[:'audit_trail_locale']
      end

      if attributes.key?(:'signers_allowed_to_decline')
        self.signers_allowed_to_decline = attributes[:'signers_allowed_to_decline']
      else
        self.signers_allowed_to_decline = false
      end

      if attributes.key?(:'email_notification')
        self.email_notification = attributes[:'email_notification']
      end

      if attributes.key?(:'template_placeholders')
        self.template_placeholders = attributes[:'template_placeholders']
      end

      if attributes.key?(:'archiving')
        self.archiving = attributes[:'archiving']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @name.to_s.length > 128
        invalid_properties.push('invalid value for "name", the character length must be smaller than or equal to 128.')
      end

      if @name.to_s.length < 1
        invalid_properties.push('invalid value for "name", the character length must be great than or equal to 1.')
      end

      if @delivery_mode.nil?
        invalid_properties.push('invalid value for "delivery_mode", delivery_mode cannot be nil.')
      end

      if !@email_custom_note.nil? && @email_custom_note.to_s.length > 500
        invalid_properties.push('invalid value for "email_custom_note", the character length must be smaller than or equal to 500.')
      end

      pattern = Regexp.new(/^\d{4}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])$/)
      if !@expiration_date.nil? && @expiration_date !~ pattern
        invalid_properties.push("invalid value for \"expiration_date\", must conform to the pattern #{pattern}.")
      end

      if !@external_id.nil? && @external_id.to_s.length > 255
        invalid_properties.push('invalid value for "external_id", the character length must be smaller than or equal to 255.')
      end

      pattern = Regexp.new(/^[\w\-@.%+]+$/)
      if !@external_id.nil? && @external_id !~ pattern
        invalid_properties.push("invalid value for \"external_id\", must conform to the pattern #{pattern}.")
      end

      if !@documents.nil? && @documents.length > 5
        invalid_properties.push('invalid value for "documents", number of items must be less than or equal to 5.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @name.nil?
      return false if @name.to_s.length > 128
      return false if @name.to_s.length < 1
      return false if @delivery_mode.nil?
      delivery_mode_validator = EnumAttributeValidator.new('String', ["none", "email"])
      return false unless delivery_mode_validator.valid?(@delivery_mode)
      return false if !@email_custom_note.nil? && @email_custom_note.to_s.length > 500
      return false if !@expiration_date.nil? && @expiration_date !~ Regexp.new(/^\d{4}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])$/)
      return false if !@external_id.nil? && @external_id.to_s.length > 255
      return false if !@external_id.nil? && @external_id !~ Regexp.new(/^[\w\-@.%+]+$/)
      return false if !@documents.nil? && @documents.length > 5
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      if name.to_s.length > 128
        fail ArgumentError, 'invalid value for "name", the character length must be smaller than or equal to 128.'
      end

      if name.to_s.length < 1
        fail ArgumentError, 'invalid value for "name", the character length must be great than or equal to 1.'
      end

      @name = name
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] delivery_mode Object to be assigned
    def delivery_mode=(delivery_mode)
      validator = EnumAttributeValidator.new('String', ["none", "email"])
      unless validator.valid?(delivery_mode)
        fail ArgumentError, "invalid value for \"delivery_mode\", must be one of #{validator.allowable_values}."
      end
      @delivery_mode = delivery_mode
    end

    # Custom attribute writer method with validation
    # @param [Object] email_custom_note Value to be assigned
    def email_custom_note=(email_custom_note)
      if !email_custom_note.nil? && email_custom_note.to_s.length > 500
        fail ArgumentError, 'invalid value for "email_custom_note", the character length must be smaller than or equal to 500.'
      end

      @email_custom_note = email_custom_note
    end

    # Custom attribute writer method with validation
    # @param [Object] expiration_date Value to be assigned
    def expiration_date=(expiration_date)
      if expiration_date.nil?
        fail ArgumentError, 'expiration_date cannot be nil'
      end

      pattern = Regexp.new(/^\d{4}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])$/)
      if expiration_date !~ pattern
        fail ArgumentError, "invalid value for \"expiration_date\", must conform to the pattern #{pattern}."
      end

      @expiration_date = expiration_date
    end

    # Custom attribute writer method with validation
    # @param [Object] external_id Value to be assigned
    def external_id=(external_id)
      if !external_id.nil? && external_id.to_s.length > 255
        fail ArgumentError, 'invalid value for "external_id", the character length must be smaller than or equal to 255.'
      end

      pattern = Regexp.new(/^[\w\-@.%+]+$/)
      if !external_id.nil? && external_id !~ pattern
        fail ArgumentError, "invalid value for \"external_id\", must conform to the pattern #{pattern}."
      end

      @external_id = external_id
    end

    # Custom attribute writer method with validation
    # @param [Object] documents Value to be assigned
    def documents=(documents)
      if documents.nil?
        fail ArgumentError, 'documents cannot be nil'
      end

      if documents.length > 5
        fail ArgumentError, 'invalid value for "documents", number of items must be less than or equal to 5.'
      end

      @documents = documents
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          name == o.name &&
          delivery_mode == o.delivery_mode &&
          ordered_signers == o.ordered_signers &&
          reminder_settings == o.reminder_settings &&
          timezone == o.timezone &&
          email_custom_note == o.email_custom_note &&
          expiration_date == o.expiration_date &&
          template_id == o.template_id &&
          external_id == o.external_id &&
          branding_id == o.branding_id &&
          custom_experience_id == o.custom_experience_id &&
          documents == o.documents &&
          signers == o.signers &&
          workspace_id == o.workspace_id &&
          audit_trail_locale == o.audit_trail_locale &&
          signers_allowed_to_decline == o.signers_allowed_to_decline &&
          email_notification == o.email_notification &&
          template_placeholders == o.template_placeholders &&
          archiving == o.archiving
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [name, delivery_mode, ordered_signers, reminder_settings, timezone, email_custom_note, expiration_date, template_id, external_id, branding_id, custom_experience_id, documents, signers, workspace_id, audit_trail_locale, signers_allowed_to_decline, email_notification, template_placeholders, archiving].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = YousignClientV3.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
