=begin
#Public Api v3

#Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.

The version of the OpenAPI document: 3.0
Contact: contact@yousign.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'date'
require 'time'

module YousignClientV3
  class CustomExperience
    attr_accessor :id

    attr_accessor :name

    attr_accessor :landing_page_disabled

    attr_accessor :side_panel_disabled

    attr_accessor :background_color

    attr_accessor :button_color

    attr_accessor :text_color

    attr_accessor :text_button_color

    attr_accessor :disabled_notifications

    attr_accessor :email_logo_disabled

    attr_accessor :email_header_text_disabled

    attr_accessor :email_footer_signature_disabled

    attr_accessor :email_expiration_text_disabled

    attr_accessor :recipients_activity_disabled

    attr_accessor :download_documents_disabled

    attr_accessor :redirect_urls

    attr_accessor :logo

    attr_accessor :source

    attr_accessor :created_at

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'name' => :'name',
        :'landing_page_disabled' => :'landing_page_disabled',
        :'side_panel_disabled' => :'side_panel_disabled',
        :'background_color' => :'background_color',
        :'button_color' => :'button_color',
        :'text_color' => :'text_color',
        :'text_button_color' => :'text_button_color',
        :'disabled_notifications' => :'disabled_notifications',
        :'email_logo_disabled' => :'email_logo_disabled',
        :'email_header_text_disabled' => :'email_header_text_disabled',
        :'email_footer_signature_disabled' => :'email_footer_signature_disabled',
        :'email_expiration_text_disabled' => :'email_expiration_text_disabled',
        :'recipients_activity_disabled' => :'recipients_activity_disabled',
        :'download_documents_disabled' => :'download_documents_disabled',
        :'redirect_urls' => :'redirect_urls',
        :'logo' => :'logo',
        :'source' => :'source',
        :'created_at' => :'created_at'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'name' => :'String',
        :'landing_page_disabled' => :'Boolean',
        :'side_panel_disabled' => :'Boolean',
        :'background_color' => :'String',
        :'button_color' => :'String',
        :'text_color' => :'String',
        :'text_button_color' => :'String',
        :'disabled_notifications' => :'Array<CustomExperienceDisabledNotificationsType>',
        :'email_logo_disabled' => :'Boolean',
        :'email_header_text_disabled' => :'Boolean',
        :'email_footer_signature_disabled' => :'Boolean',
        :'email_expiration_text_disabled' => :'Boolean',
        :'recipients_activity_disabled' => :'Boolean',
        :'download_documents_disabled' => :'Boolean',
        :'redirect_urls' => :'CustomExperienceRedirectUrls',
        :'logo' => :'String',
        :'source' => :'CustomExperienceSource',
        :'created_at' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'background_color',
        :'button_color',
        :'text_color',
        :'text_button_color',
        :'logo',
        :'source',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `YousignClientV3::CustomExperience` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `YousignClientV3::CustomExperience`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'landing_page_disabled')
        self.landing_page_disabled = attributes[:'landing_page_disabled']
      else
        self.landing_page_disabled = nil
      end

      if attributes.key?(:'side_panel_disabled')
        self.side_panel_disabled = attributes[:'side_panel_disabled']
      else
        self.side_panel_disabled = nil
      end

      if attributes.key?(:'background_color')
        self.background_color = attributes[:'background_color']
      else
        self.background_color = nil
      end

      if attributes.key?(:'button_color')
        self.button_color = attributes[:'button_color']
      else
        self.button_color = nil
      end

      if attributes.key?(:'text_color')
        self.text_color = attributes[:'text_color']
      else
        self.text_color = nil
      end

      if attributes.key?(:'text_button_color')
        self.text_button_color = attributes[:'text_button_color']
      else
        self.text_button_color = nil
      end

      if attributes.key?(:'disabled_notifications')
        if (value = attributes[:'disabled_notifications']).is_a?(Array)
          self.disabled_notifications = value
        end
      else
        self.disabled_notifications = nil
      end

      if attributes.key?(:'email_logo_disabled')
        self.email_logo_disabled = attributes[:'email_logo_disabled']
      else
        self.email_logo_disabled = nil
      end

      if attributes.key?(:'email_header_text_disabled')
        self.email_header_text_disabled = attributes[:'email_header_text_disabled']
      else
        self.email_header_text_disabled = nil
      end

      if attributes.key?(:'email_footer_signature_disabled')
        self.email_footer_signature_disabled = attributes[:'email_footer_signature_disabled']
      else
        self.email_footer_signature_disabled = nil
      end

      if attributes.key?(:'email_expiration_text_disabled')
        self.email_expiration_text_disabled = attributes[:'email_expiration_text_disabled']
      else
        self.email_expiration_text_disabled = nil
      end

      if attributes.key?(:'recipients_activity_disabled')
        self.recipients_activity_disabled = attributes[:'recipients_activity_disabled']
      else
        self.recipients_activity_disabled = nil
      end

      if attributes.key?(:'download_documents_disabled')
        self.download_documents_disabled = attributes[:'download_documents_disabled']
      else
        self.download_documents_disabled = nil
      end

      if attributes.key?(:'redirect_urls')
        self.redirect_urls = attributes[:'redirect_urls']
      else
        self.redirect_urls = nil
      end

      if attributes.key?(:'logo')
        self.logo = attributes[:'logo']
      else
        self.logo = nil
      end

      if attributes.key?(:'source')
        self.source = attributes[:'source']
      else
        self.source = nil
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @landing_page_disabled.nil?
        invalid_properties.push('invalid value for "landing_page_disabled", landing_page_disabled cannot be nil.')
      end

      if @side_panel_disabled.nil?
        invalid_properties.push('invalid value for "side_panel_disabled", side_panel_disabled cannot be nil.')
      end

      if @disabled_notifications.nil?
        invalid_properties.push('invalid value for "disabled_notifications", disabled_notifications cannot be nil.')
      end

      if @email_logo_disabled.nil?
        invalid_properties.push('invalid value for "email_logo_disabled", email_logo_disabled cannot be nil.')
      end

      if @email_header_text_disabled.nil?
        invalid_properties.push('invalid value for "email_header_text_disabled", email_header_text_disabled cannot be nil.')
      end

      if @email_footer_signature_disabled.nil?
        invalid_properties.push('invalid value for "email_footer_signature_disabled", email_footer_signature_disabled cannot be nil.')
      end

      if @email_expiration_text_disabled.nil?
        invalid_properties.push('invalid value for "email_expiration_text_disabled", email_expiration_text_disabled cannot be nil.')
      end

      if @recipients_activity_disabled.nil?
        invalid_properties.push('invalid value for "recipients_activity_disabled", recipients_activity_disabled cannot be nil.')
      end

      if @download_documents_disabled.nil?
        invalid_properties.push('invalid value for "download_documents_disabled", download_documents_disabled cannot be nil.')
      end

      if @redirect_urls.nil?
        invalid_properties.push('invalid value for "redirect_urls", redirect_urls cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @landing_page_disabled.nil?
      return false if @side_panel_disabled.nil?
      return false if @disabled_notifications.nil?
      return false if @email_logo_disabled.nil?
      return false if @email_header_text_disabled.nil?
      return false if @email_footer_signature_disabled.nil?
      return false if @email_expiration_text_disabled.nil?
      return false if @recipients_activity_disabled.nil?
      return false if @download_documents_disabled.nil?
      return false if @redirect_urls.nil?
      return false if @created_at.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          name == o.name &&
          landing_page_disabled == o.landing_page_disabled &&
          side_panel_disabled == o.side_panel_disabled &&
          background_color == o.background_color &&
          button_color == o.button_color &&
          text_color == o.text_color &&
          text_button_color == o.text_button_color &&
          disabled_notifications == o.disabled_notifications &&
          email_logo_disabled == o.email_logo_disabled &&
          email_header_text_disabled == o.email_header_text_disabled &&
          email_footer_signature_disabled == o.email_footer_signature_disabled &&
          email_expiration_text_disabled == o.email_expiration_text_disabled &&
          recipients_activity_disabled == o.recipients_activity_disabled &&
          download_documents_disabled == o.download_documents_disabled &&
          redirect_urls == o.redirect_urls &&
          logo == o.logo &&
          source == o.source &&
          created_at == o.created_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, name, landing_page_disabled, side_panel_disabled, background_color, button_color, text_color, text_button_color, disabled_notifications, email_logo_disabled, email_header_text_disabled, email_footer_signature_disabled, email_expiration_text_disabled, recipients_activity_disabled, download_documents_disabled, redirect_urls, logo, source, created_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = YousignClientV3.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
