=begin
#Public Api v3

#Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.

The version of the OpenAPI document: 3.0
Contact: contact@yousign.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'date'
require 'time'

module YousignClientV3
  class CustomExperienceDisabledNotificationsType
    APPROVER_EXPIRATION_DATE_REMINDER = "approver.expiration_date_reminder".freeze
    APPROVER_CANCELED = "approver.canceled".freeze
    APPROVER_EXPIRATION_DATE_UPDATED = "approver.expiration_date_updated".freeze
    FOLLOWER_APPROVED = "follower.approved".freeze
    FOLLOWER_CANCELED = "follower.canceled".freeze
    FOLLOWER_COMPLETED = "follower.completed".freeze
    FOLLOWER_EXPIRED = "follower.expired".freeze
    FOLLOWER_REJECTED = "follower.rejected".freeze
    FOLLOWER_SIGNED = "follower.signed".freeze
    SENDER_APPROVED = "sender.approved".freeze
    SENDER_CANCELED = "sender.canceled".freeze
    SENDER_COMPLETED = "sender.completed".freeze
    SENDER_REJECTED = "sender.rejected".freeze
    SENDER_SIGNED = "sender.signed".freeze
    SIGNER_EXPIRATION_DATE_REMINDER = "signer.expiration_date_reminder".freeze
    SIGNER_CANCELED = "signer.canceled".freeze
    SIGNER_COMPLETED = "signer.completed".freeze
    SIGNER_SIGNED = "signer.signed".freeze
    SIGNER_EXPIRATION_DATE_UPDATED = "signer.expiration_date_updated".freeze
    SIGNER_SIGNATURE_REQUESTED = "signer.signature_requested".freeze

    def self.all_vars
      @all_vars ||= [APPROVER_EXPIRATION_DATE_REMINDER, APPROVER_CANCELED, APPROVER_EXPIRATION_DATE_UPDATED, FOLLOWER_APPROVED, FOLLOWER_CANCELED, FOLLOWER_COMPLETED, FOLLOWER_EXPIRED, FOLLOWER_REJECTED, FOLLOWER_SIGNED, SENDER_APPROVED, SENDER_CANCELED, SENDER_COMPLETED, SENDER_REJECTED, SENDER_SIGNED, SIGNER_EXPIRATION_DATE_REMINDER, SIGNER_CANCELED, SIGNER_COMPLETED, SIGNER_SIGNED, SIGNER_EXPIRATION_DATE_UPDATED, SIGNER_SIGNATURE_REQUESTED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if CustomExperienceDisabledNotificationsType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #CustomExperienceDisabledNotificationsType"
    end
  end
end
