=begin
#Public Api v3

#Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.

The version of the OpenAPI document: 3.0
Contact: contact@yousign.com
Generated by: https://openapi-generator.tech
Generator version: 7.11.0

=end

require 'date'
require 'time'

module YousignClientV3
  class SignerCustomText
    attr_accessor :request_subject

    attr_accessor :request_body

    attr_accessor :reminder_subject

    attr_accessor :reminder_body

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'request_subject' => :'request_subject',
        :'request_body' => :'request_body',
        :'reminder_subject' => :'reminder_subject',
        :'reminder_body' => :'reminder_body'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'request_subject' => :'String',
        :'request_body' => :'String',
        :'reminder_subject' => :'String',
        :'reminder_body' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'request_subject',
        :'request_body',
        :'reminder_subject',
        :'reminder_body'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `YousignClientV3::SignerCustomText` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `YousignClientV3::SignerCustomText`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'request_subject')
        self.request_subject = attributes[:'request_subject']
      else
        self.request_subject = nil
      end

      if attributes.key?(:'request_body')
        self.request_body = attributes[:'request_body']
      else
        self.request_body = nil
      end

      if attributes.key?(:'reminder_subject')
        self.reminder_subject = attributes[:'reminder_subject']
      else
        self.reminder_subject = nil
      end

      if attributes.key?(:'reminder_body')
        self.reminder_body = attributes[:'reminder_body']
      else
        self.reminder_body = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @request_subject.to_s.length > 150
        invalid_properties.push('invalid value for "request_subject", the character length must be smaller than or equal to 150.')
      end

      if @request_subject.to_s.length < 1
        invalid_properties.push('invalid value for "request_subject", the character length must be great than or equal to 1.')
      end

      if @request_body.to_s.length > 2000
        invalid_properties.push('invalid value for "request_body", the character length must be smaller than or equal to 2000.')
      end

      if @request_body.to_s.length < 1
        invalid_properties.push('invalid value for "request_body", the character length must be great than or equal to 1.')
      end

      if @reminder_subject.to_s.length > 150
        invalid_properties.push('invalid value for "reminder_subject", the character length must be smaller than or equal to 150.')
      end

      if @reminder_subject.to_s.length < 1
        invalid_properties.push('invalid value for "reminder_subject", the character length must be great than or equal to 1.')
      end

      if @reminder_body.to_s.length > 2000
        invalid_properties.push('invalid value for "reminder_body", the character length must be smaller than or equal to 2000.')
      end

      if @reminder_body.to_s.length < 1
        invalid_properties.push('invalid value for "reminder_body", the character length must be great than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @request_subject.to_s.length > 150
      return false if @request_subject.to_s.length < 1
      return false if @request_body.to_s.length > 2000
      return false if @request_body.to_s.length < 1
      return false if @reminder_subject.to_s.length > 150
      return false if @reminder_subject.to_s.length < 1
      return false if @reminder_body.to_s.length > 2000
      return false if @reminder_body.to_s.length < 1
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] request_subject Value to be assigned
    def request_subject=(request_subject)
      if !request_subject.nil? && request_subject.to_s.length > 150
        fail ArgumentError, 'invalid value for "request_subject", the character length must be smaller than or equal to 150.'
      end

      if !request_subject.nil? && request_subject.to_s.length < 1
        fail ArgumentError, 'invalid value for "request_subject", the character length must be great than or equal to 1.'
      end

      @request_subject = request_subject
    end

    # Custom attribute writer method with validation
    # @param [Object] request_body Value to be assigned
    def request_body=(request_body)
      if !request_body.nil? && request_body.to_s.length > 2000
        fail ArgumentError, 'invalid value for "request_body", the character length must be smaller than or equal to 2000.'
      end

      if !request_body.nil? && request_body.to_s.length < 1
        fail ArgumentError, 'invalid value for "request_body", the character length must be great than or equal to 1.'
      end

      @request_body = request_body
    end

    # Custom attribute writer method with validation
    # @param [Object] reminder_subject Value to be assigned
    def reminder_subject=(reminder_subject)
      if !reminder_subject.nil? && reminder_subject.to_s.length > 150
        fail ArgumentError, 'invalid value for "reminder_subject", the character length must be smaller than or equal to 150.'
      end

      if !reminder_subject.nil? && reminder_subject.to_s.length < 1
        fail ArgumentError, 'invalid value for "reminder_subject", the character length must be great than or equal to 1.'
      end

      @reminder_subject = reminder_subject
    end

    # Custom attribute writer method with validation
    # @param [Object] reminder_body Value to be assigned
    def reminder_body=(reminder_body)
      if !reminder_body.nil? && reminder_body.to_s.length > 2000
        fail ArgumentError, 'invalid value for "reminder_body", the character length must be smaller than or equal to 2000.'
      end

      if !reminder_body.nil? && reminder_body.to_s.length < 1
        fail ArgumentError, 'invalid value for "reminder_body", the character length must be great than or equal to 1.'
      end

      @reminder_body = reminder_body
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          request_subject == o.request_subject &&
          request_body == o.request_body &&
          reminder_subject == o.reminder_subject &&
          reminder_body == o.reminder_body
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [request_subject, request_body, reminder_subject, reminder_body].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = YousignClientV3.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
