# -*- encoding: utf-8 -*-

=begin
#Public Api v3

#Build the best experience of digital signature through your own platform. Increase your conversion rates, leverage your data and reduce your costs with Yousign API.

The version of the OpenAPI document: 3.0
Contact: contact@yousign.com
Generated by: https://openapi-generator.tech
Generator version: 7.11.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "yousign_client_v3/version"

Gem::Specification.new do |s|
  s.name        = "yousign_client_v3"
  s.version     = YousignClientV3::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Cashbee"]
  s.email       = ["developers@cashbee.fr"]
  s.homepage    = "https://github.com/cashbee-team/yousign_client_v3"
  s.summary     = "Yousign Client API V3"
  s.description = "Yousign Client API V3"
  s.license     = ""
  s.required_ruby_version = ">= 2.7"
  s.metadata = {}

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
